name: 意见/建议
description: 对此鼠标指针提出一些意见/建议
title: "[意见/建议]"  
labels: ["待确认"]
body:
  - type: markdown
    attributes:
      value: |
        **请填写以下信息，带 * 的为必填项** 

  - type: textarea
    id: bugname
    attributes:
      label: "意见/建议"
      description: "如果你对此鼠标指针有一些意见或建议，欢迎提出"
      placeholder: "在此详细描述你的意见/建议"
    validations:
      required: true
